### ISSUE TITLE
Modifying train speed by clicking with a high CPS on a model

### ISSUE THREAD

**Issue by ryando123** [bergerhealer/TrainCarts#413] opened 2021-04-13 12:07 UTC
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): 991
- TrainCarts Version (`/train version`): 826
- Server Type and Version (`/version`): Paper 1.16.4

----
### Description
If you click on a model with a high CPS the train slows down while it's not supposed to go any slower. If you do this with multiple people there's a chance the train will completely stop or roll back.

### Expected behavior
To keep rolling at the speed it's supposed to go.

### Actual behavior
The speed of the train changes.

### Steps to reproduce
1. Spawn a model and make sure you don't have permission to break the train.
2. Preferably install an auto clicker and make sure it runs at a high speed.
3. Make the train go over a track at a slow speed (so you are able to constantly click on the model)
4. Click on the model (and make sure your cursor stays pointed to the model) and shift at the same time
5. After a few seconds you notice the speed has changed and/or the entire train stopped/is rolling back.

X. If it didn't work try it again.

### Additional Information
Here's a video of it -> https://www.youtube.com/watch?v=KIZSJjCXzOw
In the first part, I click on the model at a high speed and it eventually goes way slower than it's supposed to go. In the second part, the train runs normally so you can compare both speeds.

**Comment by ryando123** [comment] 2021-04-13 14:32
Here's a video of where the train stops and goes in the other direction
-> https://www.youtube.com/watch?v=abJkVzfw0eo

**Comment by djbenbe** [comment] 2021-04-13 15:51
this is not a bug. there is a command that you can no longer push the train / train allowplayertake false

**Comment by ryando123** [comment] 2021-04-13 16:40
It seems like that didn't fix the issue, after changing the setting it still happens. Here's again a video after executing the command: https://www.youtube.com/watch?v=pfv-Tb7VRT0

**Comment by djbenbe** [comment] 2021-04-13 19:40
did you do the train edit and then run that command and then saved?

**Comment by ryando123** [comment] 2021-04-13 19:42
Ye we did that, however I will be testing some other properties soon (such as godmode and allowManualMove). I'll see if those others have effect.

**Comment by djbenbe** [comment] 2021-04-13 19:46
yes I did tests myself. does not work.

**Comment by bergerkiller** [comment] 2021-04-17 16:28
is it Left-click (damage) or right-click (enter) that causes this problem?

**Comment by ryando123** [comment] 2021-04-18 20:55
Left-click (damage)

**Comment by bergerkiller** [comment] 2021-05-11 23:23
https://github.com/bergerhealer/TrainCarts/commit/245d5fe115a5dc2528e505992c66220d2fc76ee8 should be fixed now. This was vanilla minecraft behavior that cannot easily be turned off through Bukkit API alone. I've had to hack in some stuff.

```
        // Note: When a player is sprinting and damaging the Minecart, or uses
        //       a weapon with knockback, the minecart is given a 'push'.
        //       When collision with this entity/player is disabled, this is undesirable.
        //       To disable this behavior, we return false from this method, causing
        //       all the extra 'knockback' code to be skipped internally. There is no
        //       Bukkit event we can handle to disable this otherwise.
        boolean executePostLogic = true;
        if (damager instanceof HumanEntity) {
            ItemStack itemInMainHand = HumanHand.getItemInMainHand((HumanEntity) damager);
            boolean willDoKnockback = false;
            if (itemInMainHand != null &&
                    itemInMainHand.hasItemMeta() &&
                    itemInMainHand.getItemMeta().hasEnchant(Enchantment.KNOCKBACK)
            ) {
                willDoKnockback = true;
            } else if (damager instanceof Player && ((Player) damager).isSprinting()) {
                willDoKnockback = true;
            }
            if (willDoKnockback) {
                if (this.isUnloaded()) {
                    executePostLogic = false; // better safe than sorry
                } else if (!this.getGroup().getProperties().getCollisionMode(damager).permitsKnockback()) {
                    executePostLogic = false;
                }
            }
        }
```

**Closed** 2021-05-30 08:55 UTC
Labels: A. bug (minecraft), D. resolved (requires updating of bk/tc)
