### ISSUE TITLE
Weird Glitch were minecarts stop or go in the ground

### ISSUE THREAD

**Issue by woeterman94** [bergerhealer/TrainCarts#53] opened 2016-03-11 14:17 UTC
##### Spigot version: 1.8.9

<hr>

#### Problem or bug: 

Trains stop at random moments (mostly in turns) Or when going up a hill.
![1](https://cloud.githubusercontent.com/assets/5755057/13704448/589ff42a-e79c-11e5-9086-34ed6670b390.png)
In the screenshot above: The cart just stops, or goes into the ground.

![2](https://cloud.githubusercontent.com/assets/5755057/13704449/58a07b70-e79c-11e5-93c9-4c4a16263ef7.png)
In the screenshot above you can see how the train just stops and splits into two different trains.

Happens most of the time when a player is in the cart.

**Comment by mg-1999** [comment] 2016-03-11 17:40
Duplicate of #43

**Closed by mg-1999** 2016-03-11 17:40 UTC

**Comment by woeterman94** [comment] 2016-03-13 19:00
Exception I get:

6:59:41 PM [SEVERE] [Train_Carts] Failed to perform physics on train 'train1' at world_-703_24_1012:
6:59:41 PM [SEVERE] java.lang.NullPointerException

**Comment by woeterman94** [comment] 2016-03-14 12:23
@mg-1999 Why did you close this?

**Comment by mg-1999** [comment] 2016-03-14 17:15
It is the same as #43 in my point of view.
