### ISSUE TITLE
Minecarts deleted when I move away from them

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#332] opened 2020-02-19 19:05 UTC
##### Paper version: 1.15.2-build112

<hr>

#### Problem or bug:
I place minecart (any type) on rail and I go a long distance from him (500 blocks). When I go back, the minecart is not here and console show this message:
```
[17:21:01] [Server thread/WARN]: [Train_Carts] 1 carts of group 'train2' are missing! (externally edited?)
```
#### Expected behaviour:
Minecart will not be deleted.
#### Steps to reproduce:
1) Run clean server with this plugins in default config.
2) Place minecart (any type) on rail.
3) Go 500 blocks away from the minecart.
4) Go back to minecart.

**Comment by bbayu123** [comment] 2020-02-22 06:28
Looks like minecraft despawned it since the chunks are not loaded from first glance.

**Comment by bbayu123** [comment] 2020-03-07 22:07
Now that I think about it, this looks like a 3rd party plugin conflict, as Minecraft itself does not remove unloaded entities, but 3rd party plugins can. Can you send a list of plugins which you installed that claim to help to remove lag?

**Comment by Vlader97** [comment] 2020-03-08 19:40
Only BkCommonLib and TrainCarts.

**Comment by bbayu123** [comment] 2020-03-08 22:46
Seems like you may have a corrupted world then.

**Comment by bbayu123** [comment] 2020-03-08 22:46
To be fair, I'm guessing at this point, as dev isn't really responding here.

**Comment by bindingflare** [comment] 2020-03-18 11:29
Can confirm the same issue.

BkCommonLib version: **1.15.2-v2**
TrainCarts version: **1.15.2-v1**
Paper version: **1.15.2-build84**

**Problem or bug:**
When minecarts (that are identified as trains) move into unloaded chunks there seems to be a chance where this message pops up in console, and the whole train disappears from the world.

**Comment by bergerkiller** [comment] 2020-03-18 11:33
I confirmed this myself a few days ago, I'm aware of the problem. I'll see if I can look into this more deeply this afternoon. I had put this in #wip on discord:

> There is still a problem of trains disappearing (repro: trains going in circles, leave, 2 second wait, then stop server)

**Comment by bergerkiller** [comment] 2020-03-18 16:48
This is a multi-faceted issue, but further testing confirmed the exact issue.

When a chunk unloads, it restores the traincart entity to a minecart entity. It also sets the chunk 'dirty' so that it is saved. Repeatedly I can see that World isChunkLoaded() (and also internal derivatives of it) returns false during this unloading phase.

On 1.15.2-v2 prior to some purpur-related fixes, it will cause a chunk to be reloaded from disk (saving the previous first). As a result, if the chunk wasn't already marked dirty, the train entity is wiped. Once the chunk is loaded again (with the entity wiped) then markDirty() is done on that chunk. Kinda pointless.

On 1.15.2-v3 it no longer loads chunks this way to fix a corruption bug. As a result markDirty() isn't called at all on that version. This causes the same bug to appear.

I'm now looking into if there is a way to retrieve the chunk being unloaded at the time markDirty() must be called, since getting the loaded chunk doesn't work. I'll report back.

**Comment by bbayu123** [comment] 2020-03-20 08:06
Thank you community. We have received more than 4 reports on the same issue, and we understand how this affects your systems. We are looking into it, and a potential fix is on the way. Please bear with us for a bit longer. In the meanwhile, if you don't mind turning on keepChunksLoaded, you may do so. Otherwise, stay tuned, and we will report back immediately once a patch has been issued.

**Comment by bergerkiller** [comment] 2020-03-21 00:38
So I've found several things were broken on Minecraft 1.14 and later:
1. Entity was not replaced in nms World entitiesByUUID
2. Entity Tracker Entry referred to the old entity after replacing
3. Entity Tracker Entry State was not copied when replacing, so when network was swapped, state was lost
4. It failed to replace the entity when the chunk was unloaded and in the stage of being saved (on shutdown, particularly)
5. Forced chunk was unloaded too soon, so with keep chunks loaded this could cause issues on plugin shutdown

So this fixes an issue that exists that, when you log off far from spawn (but still close enough, apparently) and then stop the server, restart it, and join, that the entity is gone. I do not know whether/if this also fixes entities disappearing when you move away from chunks and return to them.

https://github.com/bergerhealer/BKCommonLib/commit/4cab3aa42e1feb15e10c783135e0791d81084f68
https://github.com/bergerhealer/TrainCarts/commit/cbbd7b850276308560bb52349ac3e7a501053a25

https://ci.mg-dev.eu/job/BKCommonLib/737/
https://ci.mg-dev.eu/job/TrainCarts/602/

Please let me know if the issue persists

**Comment by bbayu123** [comment] 2020-03-24 20:13
Thanks for the update Berger, marking as resolved, will close when someone can confirm that it is fixed on their own server.

**Comment by Vlader97** [comment] 2020-03-31 10:58
It is fixed.
Thanks a lot.

**Closed** 2020-03-31 12:20 UTC
Labels: A. bug (traincarts), D. resolved (requires updating of bk/tc)
