### ISSUE TITLE
The latest 1.14.x builds cause lag

### ISSUE THREAD

**Issue by RealCorebb** [bergerhealer/TrainCarts#272] opened 2019-07-03 05:03 UTC
##### Spigot version:Papermc 1.14.3 build #122

<hr>

#### Steps to reproduce:Just load BkCommonLib and TrainCarts. Sometimes when i unload TrainCarts and reload again,the problem disppears.But mostly they always cause lag.
![QQ截图20190703130152](https://user-images.githubusercontent.com/33654314/60564583-d53f6b00-9d92-11e9-8a0e-b90bfdd978bc.png)

Timings:https://timings.aikar.co/?id=1579d7a3e54941e598678eaf3e5460e0

**Comment by RealCorebb** [comment] 2019-07-03 05:08
I've been trying to load both plug-ins for a month now and then（From 1.14.1 to 1.14.3 and the builds from June to Now), but it seems like there's always been a problem, I really like these,and i enjoy it without any problems Last year in 1.13.so I raise the issue.Thank you for your efforts

**Comment by timvango** [comment] 2019-07-03 07:50
I think I'm experiencing the same (or at least a comparable) issue.
This is a summary of the report I made on Discord a few days ago:

I'm having some problems with the performance of my server. I've removed all the plugins and re-added them one by one. It looks like TC is causing some troubles somehow. If I do not have it, my average TPS is 19.9-20. When I add it, the TPS drops to an average of 4. I've made a timings report: https://timings.spigotmc.org/?url=woveyalogu. 
I do not have much experience with these reports, so I might be wrong, but it looks like BKCommonLib and TC are causing quite some delays?
Spigot: 1.14.2-R0.1-SNAPSHOT
BKCommonLib: 1.14.2-v1-SNAPSHOT
TC:  1.14.2-v1-SNAPSHOT

**Answer:**
From what i can see, it seems like something is unloading chunks which tc things shouldn't be unloaded, but without much information we can't see what's causing it. If possible, can you install a plugin called Spark (https://www.spigotmc.org/resources/spark.57242/) and use the command /spark sampler --timeout 600 to capture a 10 minute spark profile?

**Spark report**
https://sparkprofiler.github.io/#Sv2AVargvs

**Answer**
ok.... according to that profile... 84.67% of the time is being wasted on `org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState()`
which means the lag is caused by Spigot's extremely inefficient stuff
@bergerkiller is there a way to fix that?
i mean, is there a better algorithm that doesn't make the server cry?

**bergerkiller**
and this is why this class exists
https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/conversion/blockstate/BlockStateConversion.java
but I dont think it really fully will fix the problems.
the reason it is so slow is because bukkit decided it was a good idea to create a copy of the entire object ('snapshot') at the time getState() is called, despite it 99.99% never being used by anyone
that conversion utility above gets around a related issue, that getState() causes chunk loads, which you dont want during a ChunkLoadEvent
unfortunately that is exactly what the issue is https://puu.sh/DLwef/4817dd5df2.jpg
Would be interesting if I could somehow sabotage the snapshot logic so it doesnt occur

**Comment by bergerkiller** [comment] 2019-07-03 12:55
This and related issues are why the 1.14 builds haven't been released on spigot yet. The issue is there, sometimes to the point the server freezes entirely. I have noticed this too while testing. In Light Cleaner you can notice that it takes a very long time to actually load the chunks prior to fixing the light, dragging TPS way down.

Something just isn't right in the server.

**Comment by RealCorebb** [comment] 2019-07-03 12:58
> This and related issues are why the 1.14 builds haven't been released on spigot yet. The issue is there, sometimes to the point the server freezes entirely. I have noticed this too while testing. In Light Cleaner you can notice that it takes a very long time to actually load the chunks prior to fixing the light, dragging TPS way down.
> 
> Something just isn't right in the server.
> 
> I've been waiting for quite a long while now for spigot developers to come with a fix, but I'm afraid it will never come. I may have to just write my own 'getChunkat(x, z)' function with a workaround. It's just that this bricks pretty much the entirety of the Bukkit API that I'm still using...

Thanks for reply.Looking forward to

**Comment by bergerkiller** [comment] 2019-07-03 15:59
I will attempt a null-construction of CraftBlockState and assigning the relevant fields manually. When I have a build ready I will post it here. It might hurt stability though.

**Comment by bergerkiller** [comment] 2019-07-03 17:34
@timvango can you see if there is any improvement to your timings with this fix? If there are any errors let me know. https://github.com/bergerhealer/BKCommonLib/commit/3ca4ba68838782b7b8b0c1264d6eaa23c83ed5d5

https://ci.mg-dev.eu/job/BKCommonLib/566/

**Comment by RealCorebb** [comment] 2019-07-04 03:29
> @timvango can you see if there is any improvement to your timings with this fix? If there are any errors let me know. [bergerhealer/BKCommonLib@3ca4ba6](https://github.com/bergerhealer/BKCommonLib/commit/3ca4ba68838782b7b8b0c1264d6eaa23c83ed5d5)
> 
> https://ci.mg-dev.eu/job/BKCommonLib/566/

Everything works fine. TPS is 20. Thanks a lot!
https://timings.aikar.co/?id=dd970c8bb0b64ab98f072a3ff0686bca

**Comment by timvango** [comment] 2019-07-04 07:51
It's a lot better now! There are still some lagg spikes (especially when traveling through the map at a high speed, so I guess the majority is coming from Spigot/Minecraft itself), but the server can actually recover from it now.
In case they can help you, I made a new timings report with the new version: https://timings.spigotmc.org/?url=epijupujaf

Thank you very much for fixing this so quickly!

**Comment by bergerkiller** [comment] 2019-07-04 11:17
That is great to hear! I notice that onChunkUnload in traincarts is still rather slow, likely because of the getBlockStates call, so there is still some improvement to be had. I'll dig into that a bit more later.

**Comment by bergerkiller** [comment] 2019-07-04 22:00
@timvango can you test this test build out, where I've added additional timings for the different block state conversions that occur? I want to pinpoint what is still causing 33% tps usage in your case.

https://www.dropbox.com/s/4flortin8e47kno/BKCommonLib-1.14.3-v1-SNAPSHOT.jar?dl=0

**Comment by timvango** [comment] 2019-07-05 07:53
Here you go: https://timings.spigotmc.org/?url=ajuvojawex

**Comment by bergerkiller** [comment] 2019-07-05 11:25
@timvango sorry, I think I messed up and the file I linked was incorrect. Try this one instead: https://www.dropbox.com/s/aak8x8gp0wbf97t/BKCommonLib-1.14.3-v1-SNAPSHOT_timings.jar?dl=0

Triple-checked it this time

**Comment by timvango** [comment] 2019-07-05 12:18
No problem, here is the timings report of the correct version: https://timings.spigotmc.org/?url=adikulasuz

**Comment by bergerkiller** [comment] 2019-07-05 12:25
It's crazy how many chunk loads and unloads happen. Can this actually be correct? In that period it had about 2 million chunk unloads. Perhaps you can check if the same kind of thing happens when bkcommonlib/traincarts isnt installed.

At least I know what to look at now specifically. Command blocks and signs, likely because they create a copy of the data and store it. There might be a way to fix that by making a custom Sign BlockState implementation that doesn't create a copy.

**Comment by timvango** [comment] 2019-07-05 15:35
Timings without BKCommonLib and Traincarts: https://timings.spigotmc.org/?url=rufavifaxu

**Comment by bergerkiller** [comment] 2019-07-05 15:40
Yeah clear as day BKCommonLib or Traincarts is making it far worse. Without it, from WorldGuard's BukkitRegionContainer$1::onChunkLoad(ChunkLoadEvent) I can see that its at about 0.7 chunk load/unload events per tick. With BKC/TC installed its at 36 per tick.

I think it is rapidly triggering multiple chunk load/unload events for the same chunk.

Do you have any trains with keep chunks loaded on? Do these trains drive around? Are there many of them?

**Comment by timvango** [comment] 2019-07-05 15:50
According to the /train list command, there are 20 trains on the server of which 0 are moving.
All trains have keepChunksLoaded set to true.

**Comment by bergerkiller** [comment] 2019-07-05 16:17
while I dont expect it, yeah, check to see if just running BKCommonLib has this effect. It could be some background process, like the logic for maps in item frames

**Comment by timvango** [comment] 2019-07-05 17:48
You are right, without TC there is basically no impact at all: https://timings.spigotmc.org/?url=ejiyujiguc

**Comment by bergerkiller** [comment] 2019-07-05 18:58
In an effort to trace down what it could be: this version of bkcommonlib has the asynchronous chunk loading, and the chunk unload request, disabled for the forced chunk API. Traincarts uses this (relatively new) api to keep chunks loaded. It might hurt in tps when trains are moving as it's loading chunk synchronously. But it may also fix these problems and help tps.

Run it with bkc and tc.

https://www.dropbox.com/s/4flortin8e47kno/BKCommonLib-1.14.3-v1-SNAPSHOT_fc_change.jar?dl=0

**Comment by timvango** [comment] 2019-07-05 19:58
https://timings.spigotmc.org/?url=eweledewer

**Comment by bergerkiller** [comment] 2019-07-05 20:59
hmn, no real change there. I'll exclude that from the list of possibilities then.

For a test, can you remove all trains and run timings again? Perhaps make a backup if you dont have an automatic spawning system. In config.yml the 'all minecarts are traincarts' option should be false, so minecarts in unloaded chunks dont turn into traincarts minecarts.

**Comment by bergerkiller** [comment] 2019-07-05 23:41
I've made some changes to traincarts' redstone tracker so that it requires all neighbouring chunks of a chunk to be loaded (too) before loading the signs held inside. This may prevent loading chunks recursively while computing the redstone state of a sign, and may fix this issue that way.

https://ci.mg-dev.eu/job/BKCommonLib/568/
https://ci.mg-dev.eu/job/TrainCarts/474/

**Comment by timvango** [comment] 2019-07-06 08:38
Timings report for your first suggestion (using the fc_change build): https://timings.spigotmc.org/?url=exenumozuy

And the timings report with the new build: https://timings.spigotmc.org/?url=sikitugewe

**Comment by bergerkiller** [comment] 2019-07-06 10:36
That looks pretty much entirely fixed now, nice. I recommend to keep using those new builds, but keep an eye on any signs that seem to be misbehaving. For example, removing redstone power from a [!train] sign and the sign not activating.

**Comment by bergerkiller** [comment] 2019-07-30 23:16
All the above changes have been pushed to the projects, plus configuration option "initRedstoneWithRadius" if for some reason in the future people want the original, laggier, legacy behavior.

**Closed by bergerkiller** 2019-07-30 23:16 UTC
Labels: A. bug (bukkit/spigot), A. incompatibility (new mc versions), C. mc instability prevents progress
