### ISSUE TITLE
Error with collision

### ISSUE THREAD

**Issue by LaurenceBarnes** [bergerhealer/TrainCarts#434] opened 2021-11-02 15:04 UTC
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): 1136
- TrainCarts Version (`/train version`): 957
- Server Type and Version (`/version`): Airplane-Purpur-55

----
### Description
Travelling in a train at 24 BPS, Apparently occured when I let a train smash into a bedrock block at full speed to stop it. It stopped, but threw that error. Using "normal" minecarts, so no special modifications to the train physics except for collision with other trains being turned off.

### Expected behaviour
the train should just stop, not throw an error and the wagons stay aligned.

### Actual behaviour
It partially behaves as intended probably (since it stops), but  That should of course not happen, the train (3 wagons) were all smashed into one and it threw the error, which does not look right.

### Steps to reproduce
Do exactly what I described above.

### Additional Information
https://pastebin.com/Vghmkj96

(does not expire)

**Comment by bergerkiller** [comment] 2021-11-02 17:20
Was the train on a rail when it smashed into a block? And by 24bps I assume you mean setting maxspeed to 24b/s?

Train splitting code is wonky but at first appearances I couldn't see why it was producing a train with 0 carts. It has some checks for that. So reproducing will be key in understanding :)

**Comment by bergerkiller** [comment] 2021-11-02 17:44
https://ci.mg-dev.eu/job/TrainCarts/961/ As a first investigative thing, I made a lot of the spawn/split/group create logic a bit more strict with input validation. This should prevent zero-length trains and instead throw a more informative message.

It seems one of the carts there died on impact? Rip

**Comment by bbayu123** [comment] 2021-11-03 01:13
24 blocks per second? so 1.2 blocks per tick? That's not that fast...

**Comment by LaurenceBarnes** [comment] 2021-11-03 19:37
yep, blocks per second. I will test further tomorrow after work!
and yes, two carts either died or all three were smashed into a spot, idk, it looked cursed xD

**Comment by bergerkiller** [comment] 2021-11-03 19:51
I dont really understand how colliding with bedrock can make minecart entities die though. Was there anything nearby that couldve killed it? Like lava or something?

**Comment by LaurenceBarnes** [comment] 2021-11-03 20:42
nope, it just smashed into a block of bedrock after "floating" on bedrock because the rails ended two or three blocks earlier

**Comment by bergerkiller** [comment] 2021-11-03 21:32
![ScreenShot_2021-11-03 22-32-13](https://user-images.githubusercontent.com/957601/140195852-4f22f75d-dc14-4ba9-bfb0-88ea50087bcd.png)
No success there

**Comment by LaurenceBarnes** [comment] 2021-11-07 21:12
![2021-11-07_21 54 21](https://user-images.githubusercontent.com/77249464/140661976-8077ee6e-4ee5-46d8-9136-652c67518b9f.png)
![2021-11-07_22 10 16](https://user-images.githubusercontent.com/77249464/140661994-ea870b41-d12a-48ab-85d7-7e284b380f05.png)

that is the setup.
I tested it with the almost newest builds (BKCL 1142 and TC 962). _No error_, but the carts still stacked. They however all continued to exist, as I had to hit as many times as there are minecarts to destroy the train (which in this case, consisted of three chest carts and one normal cart, so I had to hit 4 times). So I guess it is resolved, or do you intend another behavior, such as the train not crushing like that?

**Comment by bergerkiller** [comment] 2021-11-07 21:23
If it's fixed now it's fixed I guess, the whole thing of carts merging together when derailed like that seems to be a separate issue unrelated to the error/problem. Also happens if you push carts derailed into a block, they also squish into one.

**Closed** 2021-12-19 20:40 UTC
