### ISSUE TITLE
Trains get stuck

### ISSUE THREAD

**Issue by stanneman99** [bergerhealer/TrainCarts#74] opened 2016-05-17 18:09 UTC
##### Spigot version: 1.8.8

<hr>

#### Problem or bug:
Trains get stuck in the floor after any drop.

#### Expected behaviour: 

Just cary on normal but this does not happen

#### Steps to reproduce:

Get a drop with like a train of 4 carts. with a station. It happend to me with 0.4 speed but it happens with other speeds as wel.

**Comment by stanneman99** [comment] 2016-05-17 18:10
Sorry for bad english btw

**Comment by JackDn** [comment] 2016-05-17 20:17
Duplicate of #43

**Closed** 2016-05-17 20:26 UTC
