### ISSUE TITLE
Carts turned into normal minecarts after a server restart

### ISSUE THREAD

**Issue by jingwenMC** [bergerhealer/TrainCarts#388] opened 2020-08-09 03:58 UTC
## Info

- BkCommonLib Version (`/train version`): v1.16.1-v1
- TrainCarts Version (`/train version`): v1.16.1-v1
- Server Type and Version (`/version`): Paper-773 (MC:1.9.4)

----
### Description
Carts turned into normal minecarts after a server restart , and send some error when loading

### Expected behaviour
Trains will stay all the same when I try to reboot

### Actual behaviour
Carts turned into normal minecarts and won't delete with `/train fixbugged`  
And there is some error in the console when loading:
```
[05:17:23] [Server thread/INFO]: [Train_Carts] Enabling Train_Carts v1.16.1-v1
[05:17:24] [Server thread/INFO]: [Train_Carts] 7 Trains have been loaded in 1 world. (39 Minecarts)
[05:17:24] [Server thread/INFO]: [Train_Carts] 0 detector rail regions loaded covering 0 blocks
[05:17:24] [Server thread/INFO]: [Train_Carts] Restoring trains and loading nearby chunks...
[05:17:24] [Server thread/WARN]: [Train_Carts] 6 carts of group '2S602' are missing! (externally edited?)
[05:17:25] [Server thread/WARN]: [Train_Carts] 6 carts of group '2S605' are missing! (externally edited?)
[05:17:25] [Server thread/WARN]: [Train_Carts] 6 carts of group '2S604' are missing! (externally edited?)
[05:17:25] [Server thread/WARN]: [Train_Carts] 6 carts of group '2S601' are missing! (externally edited?)
[05:17:25] [Server thread/WARN]: [Train_Carts] 6 carts of group '2S603' are missing! (externally edited?)
[05:17:26] [Server thread/WARN]: [Train_Carts] Traincarts is used on a world that has 'fire-physics-event-for-redstone' set to 'false' in paper.yml
[05:17:26] [Server thread/WARN]: [Train_Carts] This may cause some Traincarts signs to malfunction on world: 'world'
[05:17:26] [Server thread/WARN]: [Train_Carts] 6 carts of group '2S606' are missing! (externally edited?)
[05:17:26] [Server thread/INFO]: [Train_Carts] Train_Carts version 1.16.1-v1 enabled! (3.393s)
```

### Steps to reproduce
1.Create a train with `keepChunksLoaded: true`
2.Restart the server
3.The train disappeared and send the error when loading

### Additional Information
No

**Comment by bbayu123** [comment] 2020-08-09 07:29
Duplicate of #289

This happening on 1.9.4 is a new thing for us...

**Comment by bbayu123** [comment] 2020-08-09 07:31
Duplicate of #289

**Closed** 2020-08-30 01:31 UTC
Labels: A. bug (traincarts), B. duplicate
