### ISSUE TITLE
I need help with this..

### ISSUE THREAD

**Issue by Jarno1804** [bergerhealer/TrainCarts#112] opened 2017-04-13 14:19 UTC
**I've tried a lot but I can not get what I need to get involved here.
Both plugins are the latest version (BKCommonLib, TrainCarts), my server is 1.9
Can you help me?**

[16:07:10 ERROR]: [Train_Carts] Failed to synchronize a network controller:
[16:07:10 ERROR]: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
[16:07:10 ERROR]:   at com.bergerkiller.bukkit.common.controller.EntityNetworkController$1.getX(EntityNetworkController.java:68)
[16:07:10 ERROR]:   at com.bergerkiller.bukkit.common.bases.mutable.VectorAbstract.distanceSquared(VectorAbstract.java:243)
[16:07:10 ERROR]:   at com.bergerkiller.bukkit.common.controller.EntityNetworkController.isVelocityChanged(EntityNetworkController.java:763)
[16:07:10 ERROR]:   at com.bergerkiller.bukkit.tc.controller.MinecartMemberNetwork.syncSelf(MinecartMemberNetwork.java:203)
[16:07:10 ERROR]:   at com.bergerkiller.bukkit.tc.controller.MinecartMemberNetwork.onSync(MinecartMemberNetwork.java:174)
[16:07:10 ERROR]:   at com.bergerkiller.bukkit.common.entity.nms.NMSEntityTrackerEntry.track(NMSEntityTrackerEntry.java:53)
[16:07:10 ERROR]:   at net.minecraft.server.v1_9_R1.EntityTracker.updatePlayers(EntityTracker.java:179)
[16:07:10 ERROR]:   at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:809)
[16:07:10 ERROR]:   at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400)
[16:07:10 ERROR]:   at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660)
[16:07:10 ERROR]:   at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559)
[16:07:10 ERROR]:   at java.lang.Thread.run(Thread.java:745)

**Comment by RyanHecht** [comment] 2017-04-13 15:43
The most current version of TrainCarts is meant for use on 1.8, not 1.9. That is likely the cause of this issue.

**Comment by mg-1999** [comment] 2017-04-14 22:04
It is indeed the error you've got. Please use 1.8.

Closing this now.

**Closed by mg-1999** 2017-04-14 22:04 UTC
