### ISSUE TITLE
Ghost trains, warnings in console (1.17 Paper)

### ISSUE THREAD

**Issue by ghost** [bergerhealer/TrainCarts#429] opened 2021-09-09 15:37 UTC
## Info
- BkCommonLib Version: v1.17.1-v3
- TrainCarts Version: v.1.17.1-v1
- Server Type and Version: Paper v1.17.1-R0.1-SNAPSHOT

----
### Console messages
There is an automatic subway system on my server using spawners. When I start the server and the spawner sign starts to work, I get this warning in console:

> [16:37:57 WARN]: java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world world: EntityMinecartRideable$mplgen14bce30a['Minecart'/149, uuid='5a178381-c268-44f6-bd10-4ea81018ecd6', l='ServerLevel[world]', x=1497.50, y=50.06, z=-721.10, cpos=[93, -46], tl=0, v=true, rR=null] ALREADY CONTAINED (This would have crashed your server)
[16:37:57 WARN]:        at net.minecraft.server.level.PlayerChunkMap.addEntity(PlayerChunkMap.java:1978)
[16:37:57 WARN]:        at net.minecraft.server.level.ChunkProviderServer.addEntity(ChunkProviderServer.java:1165)
[16:37:57 WARN]:        at net.minecraft.server.level.WorldServer$a.b(WorldServer.java:2377)
[16:37:57 WARN]:        at net.minecraft.server.level.WorldServer$a.b(WorldServer.java:2333)
[16:37:57 WARN]:        at com.bergerkiller.bukkit.common.internal.logic.EntityAddRemoveHandler_1_17$Hook.b(Unknown Source)
[16:37:57 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.e(PersistentEntitySectionManager.java:217)
[16:37:57 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[16:37:57 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[16:37:57 WARN]:        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
[16:37:57 WARN]:        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)[16:37:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[16:37:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[16:37:57 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[16:37:57 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)[16:37:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[16:37:57 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[16:37:57 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.lambda$updateChunkStatus$7(PersistentEntitySectionManager.java:265)
[16:37:57 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[16:37:57 WARN]:        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
[16:37:57 WARN]:        at java.base/java.util.stream.LongPipeline$1$1.accept(LongPipeline.java:177)
[16:37:57 WARN]:        at java.base/java.util.PrimitiveIterator$OfLong.forEachRemaining(PrimitiveIterator.java:189)
[16:37:57 WARN]:        at java.base/java.util.Spliterators$LongIteratorSpliterator.forEachRemaining(Spliterators.java:2002)
[16:37:57 WARN]:        at java.base/java.util.Spliterator$OfLong.forEachRemaining(Spliterator.java:763)
[16:37:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[16:37:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[16:37:57 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[16:37:57 WARN]:        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)[16:37:57 WARN]:        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[16:37:57 WARN]:        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
[16:37:57 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.a(PersistentEntitySectionManager.java:245)
[16:37:57 WARN]:        at net.minecraft.world.level.entity.PersistentEntitySectionManager.a(PersistentEntitySectionManager.java:230)
[16:37:57 WARN]:        at net.minecraft.server.level.PlayerChunkMap.a(PlayerChunkMap.java:2246)
[16:37:57 WARN]:        at net.minecraft.server.level.PlayerChunk.lambda$scheduleFullChunkPromotion$7(PlayerChunk.java:617)
[16:37:57 WARN]:        at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783)
[16:37:57 WARN]:        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
[16:37:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149)
[16:37:57 WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeTask(ChunkProviderServer.java:1233)
[16:37:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122)
[16:37:57 WARN]:        at net.minecraft.server.level.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1246)
[16:37:57 WARN]:        at net.minecraft.server.level.ChunkProviderServer.runTasks(ChunkProviderServer.java:839)
[16:37:57 WARN]:        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1406)
[16:37:57 WARN]:        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389)
[16:37:57 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:132)
[16:37:57 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1467)
[16:37:57 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[16:37:57 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:37:57 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

This warning is repeated 10 times (exactly as how many minecarts are set to be spawned)

Then this message appears more than 10 times repeatedly:

> [16:38:30 ERROR]: [BKCommonLib.Network] [BKCommonLib] [Network] Failed to update viewer:
[16:38:30 WARN]: java.lang.IllegalStateException: This member has no network presence and was probably unloaded
[16:38:30 WARN]:        at TrainCarts-1.17.1-v1-941.jar//com.bergerkiller.bukkit.tc.controller.components.AttachmentControllerMember.getRootAttachment(AttachmentControllerMember.java:120)
[16:38:30 WARN]:        at TrainCarts-1.17.1-v1-941.jar//com.bergerkiller.bukkit.tc.controller.components.AttachmentControllerMember.makeVisible(AttachmentControllerMember.java:290)
[16:38:30 WARN]:        at TrainCarts-1.17.1-v1-941.jar//com.bergerkiller.bukkit.tc.controller.MinecartMemberNetwork.makeVisible(MinecartMemberNetwork.java:107)
[16:38:30 WARN]:        at BKCommonLib-1.17.1-v3-1117.jar//com.bergerkiller.bukkit.common.controller.EntityNetworkController.addViewer(EntityNetworkController.java:428)
[16:38:30 WARN]:        at BKCommonLib-1.17.1-v3-1117.jar//com.bergerkiller.bukkit.common.internal.hooks.EntityTrackerEntryHook_1_14.updatePlayer(EntityTrackerEntryHook_1_14.java:72)
[16:38:30 WARN]:        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen56722ecb.invokeVA(Unknown Source)
[16:38:30 WARN]:        at BKCommonLib-1.17.1-v3-1117.jar//com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.invokeVA(ClassInterceptor.java:506)
[16:38:30 WARN]:        at BKCommonLib-1.17.1-v3-1117.jar//com.bergerkiller.mountiplex.reflection.util.fast.Invoker.invoke(Invoker.java:33)
[16:38:30 WARN]:        at net.minecraft.server.level.PlayerChunkMap$EntityTracker$mplgenf1e7d85.updatePlayer(Unknown Source)
[16:38:30 WARN]:        at net.minecraft.server.level.PlayerChunkMap$EntityTracker.updatePlayers(PlayerChunkMap.java:2303)
[16:38:30 WARN]:        at net.minecraft.server.level.PlayerChunkMap.processTrackQueue(PlayerChunkMap.java:2049)
[16:38:30 WARN]:        at net.minecraft.server.level.PlayerChunkMap.g(PlayerChunkMap.java:2070)
[16:38:30 WARN]:        at net.minecraft.server.level.ChunkProviderServer.tickChunks(ChunkProviderServer.java:1082)
[16:38:30 WARN]:        at net.minecraft.server.level.ChunkProviderServer.tick(ChunkProviderServer.java:934)
[16:38:30 WARN]:        at net.minecraft.server.level.WorldServer.doTick(WorldServer.java:731)
[16:38:30 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1619)
[16:38:30 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:479)
[16:38:30 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[16:38:30 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274)
[16:38:30 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[16:38:30 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

### What's in the game

In general, the whole system works as expected. But I've noticed that one train (probably the one spawned during this warnings) becomes invisible but still exists in my minecrfat world! It can be seen in /train list and it even triggers detector rails just as normal trains.

![2021-09-08_12 14 57](https://user-images.githubusercontent.com/90404475/132716187-79e54576-3b03-44ed-b764-546c8ecc8629.png)
![2021-09-08_12 15 07](https://user-images.githubusercontent.com/90404475/132716201-08241a60-9205-428b-bb8d-9bd967cdace7.png)
It's not a lag - an invisible train stopped at [station] sign and triggered detector rails.

The problem appears to be happening once every time traincarts plugin starts working.

----

Thank you for developing such an amazing plugin. I hope this information will help you fix this issue.

**Comment by J0schlZ** [comment] 2021-09-09 20:28
How exactly are you spawning the train?
And does this happen only if your server is starting?
Does it happen everytime the server is starting?

I have the same issue. But with trains spawned by a self created third-party-plugin.

**Comment by bergerkiller** [comment] 2021-09-09 21:04
This is almost definitely something introduced with the tuinity merge into paper, Im working on a fix

**Comment by bergerkiller** [comment] 2021-09-09 23:14
I had some trouble because DebugUtil spammed a billion entries and so I couldn't find where the bug sat. I found one bug where entities were not properly swapped out in paper/tuinity's EntitySliceManager which is indeed new. Can you confirm if this also fixes the actual error?

https://ci.mg-dev.eu/job/BKCommonLib/1118/

**Comment by Mineshafter61** [comment] 2021-09-09 23:59
A temporary fix is to always load the chunk with the spawner using an always loaded minecart. Hope this helps!

**Comment by orloff-n** [comment] 2021-09-10 08:07
> 
> 
> How exactly are you spawning the train? (Please show us the signs and or commands you are using)
> And does this happen only if your server is starting?
> Does it happen everytime the server is starting?
> 
> I have the same issue. But with trains spawned by a self created third-party-plugin.

![2021-09-10_10 45 18](https://user-images.githubusercontent.com/90404475/132819829-f332c123-8537-434e-9f9f-ee3c31836b8f.png)
1. Here is the spawner.
2. It happens either when I start the server with the spawner already switched on or when I switch on the launcher.
3. Yes, it happens every time and I found a way how to reproduce it. You need to start the server, wait for some time and connect while not being close to the spawner (around 350 blocks away in my case)

**Comment by orloff-n** [comment] 2021-09-10 08:36
> 
> 
> I had some trouble because DebugUtil spammed a billion entries and so I couldn't find where the bug sat. I found one bug where entities were not properly swapped out in paper/tuinity's EntitySliceManager which is indeed new. Can you confirm if this also fixes the actual error?
> 
> https://ci.mg-dev.eu/job/BKCommonLib/1118/

No, unfortunately it had no effect on the issue.

UPDATE: Actually, you don't even need to connect to the server. After waiting for about 30 seconds server console will get flooded with `java.lang.Throwable: [ERROR] Illegal PlayerChunkMap::addEntity for world ...` warnings. So it seems that something is wrong with loading the chunch with the spawner.

**Comment by bergerkiller** [comment] 2021-09-10 16:20
@orloff-n I see no property sign to enable keep chunks loaded for the trains. Dont the trains just unload (and stop moving), risk piling up in one spot, etc. When youre not nearby? Or do you use keepchunksloaded here?

**Comment by bergerkiller** [comment] 2021-09-10 16:25
Oh, I got it to happen with an autospawner now (and keepchunksloaded). Good advice. Ill work from here...

**Comment by orloff-n** [comment] 2021-09-10 16:27
> 
> 
> @orloff-n I see no property sign to enable keep chunks loaded for the trains. Dont the trains just unload (and stop moving), risk piling up in one spot, etc. When youre not nearby? Or do you use keepchunksloaded here?

I've set to keep chunks loaded in the config file, so no additional signs required. Trains do not unload and never did.

**Comment by bergerkiller** [comment] 2021-09-10 19:44
After trying out various things I found the problem, but I have not yet solved it.

The issue is that entity tracking (network sync stuff) isnt setup anymore during the call of world.addEntity, but is instead a tick delayed (sometimes?). Because traincarts sets a network controller, overriding the entity tracker, it registers tracking before the vanilla tracking is done. With a tick delay the vanilla tracking then tries to register itself, this fails, with the error as shown.

This workaround is a fix, but not a good fix because the train sits a whole tick without network handling.
```
            if (networkController != null) {
                CommonUtil.nextTick(() -> {
                    entity.setNetworkController(networkController);
                });
            }
```

I'll have to see if I can somehow speed up and/or skip the vanilla tracker registering.

This issue has nothing to do with tuinity, it also occurs on the oldest paper 1.17 build I got.

**Comment by bergerkiller** [comment] 2021-09-12 16:49
https://ci.mg-dev.eu/job/BKCommonLib/1119/ this seems to fix the problem for me. I could trace it down to PersistentEntityManager's checks of 'Visibility' when adding an entity. There is a property checked there of the entity (dn()) to see whether it should always be ticked & tracked.

While not ideal, traincarts trains are already always ticked, so this is the easiest way to fix the issue at the moment. I no longer saw the warnings since testing on a long track spawning 10m trains every 45s.

**Comment by bergerkiller** [comment] 2021-09-14 10:54
Anyone has feedback? Did it help? I've seen some strange things where carts seem to go missing, but Im unsure if this commit is the root cause of that or if it's a separate issue I need to look at.

**Comment by orloff-n** [comment] 2021-09-14 10:57
OK, I'll try the latest build and will provide a feedback

**Comment by orloff-n** [comment] 2021-09-14 11:20
Yes, the errors are gone, so are 'ghost' trains. I'll continue running the system for a while to see if there is anything else wrong, but for now everything seems to be working absolutely fine, like in 1.16. 

So, @bergerkiller, thank you very much for solving this issue quickly and updating your plugins! They are absolutely crucial for my city half-rpg-half-vanilla server project. BTW, would be glad to share how everything works once it's finished!

**Comment by bergerkiller** [comment] 2021-09-14 11:22
I always enjoy seeing people's creations in the general channel :)

keep me updated if anything is still broken, especially with server restarts and stuff. The 'carts are missing' warning is a reported problem someone had, so I'll have to see then what causes that.

**Comment by bbayu123** [comment] 2021-10-31 09:39
Closing issue since issue is resolved and OP's account has been deleted.

**Closed by bbayu123** 2021-10-31 09:39 UTC
Labels: D. resolved (requires updating of bk/tc), A. bug (bkcommonlib)
