### ISSUE TITLE
Train Carts, made my TPS go down to 10.

### ISSUE THREAD

**Issue by Danni122112** [bergerhealer/TrainCarts#181] opened 2017-12-26 07:12 UTC
##### Spigot version:

<hr>

#### Problem or bug:
It completely killed the perfomance of my server, check the timings for more info
https://timings.spigotmc.org/?url=qolasadoqa
#### Expected behaviour:
Not kill the perfomance of my server
#### Steps to reproduce:
I am not quite sure, I installed hte mod a few days ago, wanting to use it for some minecart system, the server however is still in developement, so did not get around to it yet. I quickly noticed that the plugin, while not even having done any commands with it yet, used 4% of the server tick.

I just shrugged it of, and hoped it would not become an issue in the future, however sadly it did.

I would appreciate a lot if you would be able to solve this, as this plugin do seem pretty interesting.

**Comment by bergerkiller** [comment] 2017-12-28 19:28
These issues have actually been fixed in the development builds thanks to someone else reporting it to me a couple weeks ago. The problem is/was that, when chunks unload, train carts did a whole lot of processing for every single sign in that chunk to find the power state and rail information. It also did this for non-TC signs. You can imagine this wreaks havoc on some servers.

There's a whole lot more that I fixed though, and since a new version is coming up soon I'd welcome you to test out the latest development builds to see if that resolves these and other performance problems.

https://ci.mg-dev.eu/job/BKCommonLib/328/
https://ci.mg-dev.eu/job/TrainCarts/207/

**Comment by Danni122112** [comment] 2018-01-02 05:08
Thanks a lot!

**Closed** 2018-01-26 12:13 UTC
