### ISSUE TITLE
ProtocolLib

### ISSUE THREAD

**Issue by ryando123** [bergerhealer/TrainCarts#261] opened 2019-05-04 17:18 UTC
##### Spigot version: 1.12.2

<hr>

#### Steps to reproduce: Remove ProtocolLib and try to sit in a model.

**Comment by bbayu123** [comment] 2019-05-05 10:27
Not really that surprising, however, it's either a bug with BK, or a working-as-intended

**Comment by bergerkiller** [comment] 2019-07-30 23:24
Can't reproduce this anymore, Im assuming it has been fixed in BKCommonLib by now.

**Closed by bergerkiller** 2019-07-30 23:24 UTC
Labels: A. bug (unidentified), C. help wanted
