### ISSUE TITLE
Property keepChunksLoaded does not work

### ISSUE THREAD

**Issue by tmakaj213** [bergerhealer/TrainCarts#158] opened 2017-08-12 03:15 UTC
##### BkCommonLib version:
BKCommonLib-1.12.1-v1

##### TrainCarts version:
TrainCarts-1.12.1-v1-SNAPSHOT

##### Spigot version:
Spigot-1.12.1

<hr>

#### Problem or bug:
I understand that there was an issue posted about this in the past, but the problem was never resolved. I have relatively long rail lines on a private SMP server of mine that travels to far distances, probably about 2,000 blocks away from a station, and a train that travels on a track does not load chunks in real-time as it passes through unloaded chunks. Therefore, if you are waiting at a far-away station that contains tracks that are in unloaded chunks, a train ends up never coming to the station. Reminder that keepchunksloaded is always set to true in defaultTrainProperties.yml, and I always check /train info. Also, when i check /train info, sometimes it will say that the train is unloaded and that i have to set keepchunksloaded to true, however, I do that and I check /train info again and it gives me the same error, that the train is unloaded. Usually, when I go to check where the train is after seeing this message, I see it stopped at a station, and it ends up moving after the 10-second interval that I set on all my stations.

#### Expected behaviour:
A train will travel along a track and, as it moves along, it loads the chunks in real-time, therefore, if there are unloaded chunks between the origin and the destination, the train will load the chunks and arrive at the station normally.

#### Steps to reproduce:
Self-Explanatory

**Comment by bergerkiller** [comment] 2017-08-12 19:58
Yes this has to be fixed, except I haven't been able to build a good test setup for it. It seems to just work for the very long test track I made. However your comment saying it says the train was unloaded is interesting. I will have to check if unload() is possible anywhere where no check for keep loaded is done.

Are you using any plugins that back up worlds or 'lag reducing' plugins that may force chunk unloads? It may be a case where chunks are unloaded without TC having the option to cancel it. I think a good solution is to run something in the background re-loading chunks when they are unloaded for keep-loaded trains.

**Comment by bergerkiller** [comment] 2017-08-12 22:50
I've given it another attempt at fixing things here. https://github.com/bergerhealer/TrainCarts/commit/6f894102dc783bd8e83b4731c56cf91186cbebf0
My tests locally with a long track and a station in the 'unloaded' area all worked fine. I will probably need your assistance in tracking this down (test on your server with a debug version of the plugin) if it is still not fixed in the current dev build.  https://ci.mg-dev.eu/job/TrainCarts/79/

**Comment by frozenMC** [comment] 2017-08-12 23:03
Will install this and test it and return with results by tonight.

**Comment by bergerkiller** [comment] 2017-08-13 14:52
Do you think its possible to send me the map in pm on spigot (Team bergerhealer) or otherwise? If I want to ever fix this I'll need to reproduce it in a proper manner. This bug has been floating around since the very beginning of TrainCarts unfortunately...

**Comment by frozenMC** [comment] 2017-08-13 19:43
Sent you an PM on spigot with the map. Hopefully that will help.

-Fro

**Comment by bergerkiller** [comment] 2017-08-13 21:03
On my initial test run, interestingly what happened was that the TrainCarts train turned into normal minecarts. They didnt respond to signs and normal physics from TC did not work. It'll take me a bit to unravel all that's going wrong but I know something isn't right.

**Comment by bergerkiller** [comment] 2017-08-13 21:17
First off, can you turn the following option to false in the TrainCarts config.yml?
```
# Whether or not chunks are only kept loaded when the train is moving
keepChunksLoadedOnlyWhenMoving: true
```

That for sure would result in trains going unloaded when they reach stations. I remember it was defaulting to true in an older version, so that may be why its incorrectly set like this. In almost all cases you dont want it to do this.

**Comment by tmakaj213** [comment] 2017-08-13 21:39
You are actually correct with turning off keepChunksLoadedOnlyWhenMoving because i tried it when i reinstalled the plugin and i saw that it was false compared to when i had it to true before. It seems that turning off that option fixes the issue for me

**Comment by bergerkiller** [comment] 2017-08-14 23:27
I will keep this ticket open in case others suffer similar issues or when new bugs related to this feature pop up (inevitable). I have released a new version which has the same changes as the last dev-build I linked.

**Comment by frozenMC** [comment] 2017-08-15 02:09
Well that was one hell of a catch. I wouldn't have thought that config
would work contrary to what I wanted it, but it does explicitly say what it
does after all. Thanks for the fix! Appreciate it -- it works like intended
now. Onwards to other fun projects!

-fro

**Closed** 2019-08-14 00:32 UTC
Labels: A. misunderstanding of usage, C. keep in open, D. resolved (requires changes by user)
