### ISSUE TITLE
Trains stops and are cut when they climb a grade

### ISSUE THREAD

**Issue by woeterman94** [bergerhealer/TrainCarts#59] opened 2016-03-29 10:22 UTC
Hi,
I installed yours train cart in 1.8 with a spigot server, but when I try to run a rollercoaster ride, the train (composed of 8 carts) is separated in to parts and stopped when he try to climb the first grade.
![2](https://cloud.githubusercontent.com/assets/5755057/13704449/58a07b70-e79c-11e5-93c9-4c4a16263ef7.png)
In the screenshot above you can see how the train just stops and splits into two different trains.

 I tried to modify the track to view if it could be better with smoother lines but that made anything.
Thanks.

**Comment by mg-1999** [comment] 2016-03-29 22:30
A possible duplicate of #43

**Comment by woeterman94** [comment] 2016-03-30 06:35
In the issue you refer to (#43):
- Trains sink in the ground.
- Trains do **not **split
- Problem caused by turns? 

In this issue
- Trains split
- Trains do not sink in the ground.
- Problem caused by hills

**Comment by mg-1999** [comment] 2016-03-30 07:14
The problems are different but the underlying problem would still be the
same. So in my point of view they are the same.

Op wo 30 mrt. 2016 08:35 schreef Wouter <notifications@github.com>:

> In the issue you refer to (#43
> <https://github.com/bergerhealer/TrainCarts/issues/43>):
>
>    - Trains sink in the ground.
>    - Trains do **not **split
>    - Problem caused by turns?
>
> In this issue
>
>    - Trains split
>    - Trains do not sink in the ground.
>    - Problem caused by hills
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/59#issuecomment-203275048>
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by woeterman94** [comment] 2016-03-30 07:46
Fine by me, as long as it will be fixed ;)

**Closed** 2016-05-14 22:40 UTC
Labels: duplicate
