### ISSUE TITLE
keepChunksLoaded doesn't work

### ISSUE THREAD

**Issue by Etienne-Wattebled** [bergerhealer/TrainCarts#134] opened 2017-06-12 21:18 UTC
##### BkCommonLib version:
1.11.2-v2
##### TrainCarts version:
1.11.2-v2
##### Spigot version:
1.11.2-R0.1-SNAPSHOT

#### Problem or bug:
keedChunksLoaded doesn't work
#### Expected behaviour:
When keedChunksLoaded is set to true in DefaultTrainProperties.yml, trains should stay and continue, player or not near trains
#### Steps to reproduce:
Easy to reproduce so nothing to add

**Comment by bergerkiller** [comment] 2017-06-15 20:09
Wish it was so easy to reproduce. What exactly are the symptoms? I need to know the following things:
- When you check /train info on a far-away train, does it say 'keeps chunks loaded: true'
- When you check /train info repeatedly, does the train move? If not, is it stuck at a station? Does it start moving again when you get closer?
- If the train does move / act like it is loaded, what makes you think it does not keep chunks loaded?

I have repeatedly tried getting a keepchunksloaded: true train to unload or get stuck far away, but nothing appears to cause it nor can I reproduce it. So for me, it's a bit of an annoying bug to fix.

**Comment by Etienne-Wattebled** [comment] 2017-06-16 12:34
Hello,

What I can say to you is that, my train lines are very, very long and TrainCarts consumes a lot of server CPU.
In fact, what I can say is that sometimes I have the impression that trains doesn't want to Spawn if I am not near...
Another bugs I have is that, a lot of time, wagons come off...
I can find a lot of time one or two wagons alone.

Thanks

**Comment by bergerkiller** [comment] 2017-06-16 16:55
A problem that does exist on Spigot is that loaded chunks does not imply that activity actually occurs in the area. On vanilla CraftBukkit this was not the case, but on Spigot things like block physics (redstone, crop growth) and also entity physics don't occur when no players are nearby. TrainCarts keeps the chunks loaded, and guarantees the trains are updated every tick, but that may not be enough when redstone doesn't trigger or something like it.

Wagons coming off does, however, sound like something to do with trains not being in loaded chunks, which is strange.

I made a minor change so it will always get (and load) a chunk, even when it did not move into that area. If this actually does fix it, that would be nice, but it's doubtful.

https://ci.mg-dev.eu/job/TrainCarts/44/

**Comment by Etienne-Wattebled** [comment] 2017-06-16 21:14
Hello,

Thank you very much. I am going to test that.
Does you think you can optimize TrainCarts in order to consume less ?

Thank you very much.

**Comment by bergerkiller** [comment] 2017-06-17 01:25
It's already getting better with the many optimizations done in BKCommonLib, replacing reflection with runtime generated code. A big performance hit right now is getBlockData, because it calls that function easily hundreds of times a tick to detect all the rails. There is currently no perfect way to fix that, but I'm reducing it bit by bit by caching this information when I can.

On my test server it could handle 600 minecarts going in a circle while staying at 20tps, so I don't think performance is that awful right now.

**Comment by Etienne-Wattebled** [comment] 2017-06-17 07:26
Hello,

Look this screen: https://postimg.org/image/z37dn5zaf/
Trains continue to come off / to come way....
Left: destroyer
RIght: Spawner

At the end of the destroyer, I put a lava hole for security if [!train] and [!cart] destroy doesn't work...

Thanks.

**Comment by bergerkiller** [comment] 2017-06-17 17:32
I have created a little test track far away from the spawn. It has a spawn sign + keepchunksloaded true property sign. They all go towards a [portal] sign teleporting them to another world (where they are destroyed), where I verify they keep coming, and they do.

https://puu.sh/wmIQz/2c71182833.png

Is there something specific I'm missing?

**Comment by Etienne-Wattebled** [comment] 2017-06-17 21:15
I don't know.
For the moment trains don't come way.

**Comment by lolzelig** [comment] 2017-07-03 11:17
Hello :)

I am also experiencing an issue with carts not moving when nobody is nearby.. which is pretty frustrating, since I've just built a whole train line, which depends on trains to keep moving when nobody is around specific areas..

The trains move a few chunks and then pile up .. :/

**Comment by Etienne-Wattebled** [comment] 2017-07-03 11:23
Hello lolzelig,

Go on ./plugins/Trains_Carts
Open the DefaultTrainProperties.yml

Is the property keepChunksLoaded set to true ?

Thanks.

**Comment by lolzelig** [comment] 2017-07-03 11:29
Yes and I've also tried to manually change the property of the trains, but it already was set to true.

**Comment by frozenMC** [comment] 2017-07-25 07:52
I have run into this very issue, with a 5-long train going in a loop. It does say that it has the keepchunkloaded property set as true, yet when it goes a reasonable distance from me the chunks unloads. 

https://i.imgur.com/cROksgA.png (I did what you suggested- repeatedly put in "/train info" until it finally got itself unloaded. 500 blocks give or take from the location in the picture.

**Comment by bergerkiller** [comment] 2017-08-15 11:45
I assume this issue is now fixed since a new issue ticket was made, where it turned out to be a configuration issue for some. (keepChunksLoadedOnlyWhenMoving). That being set incorrectly has been fixed for a while, I'm leaving the other issue ticket up for when people run into it again anyway.

**Closed by bergerkiller** 2017-08-15 11:45 UTC
