### ISSUE TITLE
Possible train destination bug

### ISSUE THREAD

**Issue by Disneykid93** [bergerhealer/TrainCarts#416] opened 2021-05-27 20:27 UTC
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): 1.16.5-v3-SNAPSHOT
- TrainCarts Version (`/train version`): 1.16.5-v2-SNAPSHOT
- Server Type and Version (`/version`): git-Purpur-1118 (MC: 1.16.5)

----
### Description
I set the destination I want on the train to reach but half the time the train will never path find to that destination when the track switch is right in front of it, or it will go down the track it's supposed to if it was already set to it and it will still say "can not be reached from here", and then it will work like it should then stop working. This has been a problem for about a year now at least for me.

### Expected behaviour
Trains should path find to the destination 100% of the time.

### Actual behaviour
50% of the time gives the error "(destination name) can not be reached from here" and continues down previously selected track.

### Steps to reproduce
Please list the steps to take, in order to reproduce the bug.

### Additional Information
Video link showing what happens- https://www.youtube.com/watch?v=3TATPmZO5DM

**Comment by bbayu123** [comment] 2021-05-28 05:49
I have a feeling that the orientation of the destination sign does not allow it to see oncoming trains, since the tcc track is kind of coming in from the back(?), but I doubt that's how destination signs work... nonetheless, a `[+train:*]` should avoid any directional problems on both the destination and the switcher, and always do a `/train reroute` if you don't see destinations working. (I'm saying this since I didn't see you do it in the video)

Alternatively, if this is really having an issue, what you can do for now is to fallback to traditional statement switchers, where you can do `1-2:d@bay2_3`, `1-3:d@bay1` or something like that. But if you need to do that for most of the signs, then this really should be something to look into...

**Comment by Disneykid93** [comment] 2021-05-28 06:15
I will be sure to give what you suggested a try, but for now that track I was showcasing is working just fine as it was in that last clip so I won't touch it until it starts acting up again.

**Comment by bbayu123** [comment] 2021-05-28 06:21
Well, as a plugin developer, knowing that something isn't working and we don't know why is a concerning thing for us, but a more concerning thing would be **something works** but **we don't know why it's working**. If we can't explain why something is working when it wasn't in the first place, then there might be something more serious going on in the background.

Anyway, up to you, I'll keep this open for a while until you can confirm it has been fixed. Alternatively, you can close this for now and reopen it at a later stage if it acts up again.

**Comment by AzonInc** [comment] 2021-06-06 20:02
I am experiencing the same issue with the following Versions:

BkCommonLib: 1.16.5-v2 Build 1000
TrainCarts: 1.16.5-v1 Build 843
Server: git-Paper-683 (MC: 1.16.5)

**Comment by bbayu123** [comment] 2021-06-06 20:27
> I am experiencing the same issue with the following Versions:
> 
> BkCommonLib: 1.16.5-v2 Build 1000
> TrainCarts: 1.16.5-v1 Build 843
> Server: git-Paper-683 (MC: 1.16.5)

Update to latest development builds and try first.

**Comment by AzonInc** [comment] 2021-06-06 21:49
> > I am experiencing the same issue with the following Versions:
> > BkCommonLib: 1.16.5-v2 Build 1000
> > TrainCarts: 1.16.5-v1 Build 843
> > Server: git-Paper-683 (MC: 1.16.5)
> 
> Update to latest development builds and try first.

Tested again with:
BkCommonLib: 1.16.5-v3-SNAPSHOT Build 1039
TrainCarts: 1.16.5-v2-SNAPSHOT Build 891
Server: git-Paper-769 (MC: 1.16.5)

It keeps switching wrong sometimes

**Comment by bbayu123** [comment] 2021-06-06 22:00
Ok... um... first thing is I need to actually see your setup. Ideally a video, but if not possible, then sufficient amount of images might work.

**Comment by AzonInc** [comment] 2021-06-06 22:32
Okay so... after further testing everything seems to work as intended even after restarting the server.

The only thing I noticed is one Error in Console but that one is not related to the main issue:
```
[00:27:14 ERROR]: [Train_Carts] Failed to perform physics on train 'train2' at test_1176_10_-389:
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib] java.util.ConcurrentModificationException
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.common.collections.List2DIterator.next(List2DIterator.java:53)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.components.SignTracker.tryUpdateActiveSigns(SignTracker.java:156)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.components.SignTracker.updateActiveSigns(SignTracker.java:115)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.components.SignTrackerGroup.refresh(SignTrackerGroup.java:196)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1455)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1384)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:2252)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:131)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedMethodInvoker$mplgen30d3ec7d.invokeVA(Unknown Source)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.invokeVA(ClassInterceptor.java:506)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.Invoker.invoke(Invoker.java:29)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.EntityMinecartRideable$mplgen124ee344.tick(Unknown Source)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.World.a(World.java:955)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by bbayu123** [comment] 2021-08-25 08:54
> Okay so... after further testing everything seems to work as intended even after restarting the server.
> 
> The only thing I noticed is one Error in Console but that one is not related to the main issue:
> 
> ```
> [00:27:14 ERROR]: [Train_Carts] Failed to perform physics on train 'train2' at test_1176_10_-389:
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib] java.util.ConcurrentModificationException
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.common.collections.List2DIterator.next(List2DIterator.java:53)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.components.SignTracker.tryUpdateActiveSigns(SignTracker.java:156)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.components.SignTracker.updateActiveSigns(SignTracker.java:115)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.components.SignTrackerGroup.refresh(SignTrackerGroup.java:196)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1455)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1384)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:2252)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:131)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedMethodInvoker$mplgen30d3ec7d.invokeVA(Unknown Source)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.invokeVA(ClassInterceptor.java:506)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.Invoker.invoke(Invoker.java:29)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.EntityMinecartRideable$mplgen124ee344.tick(Unknown Source)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.World.a(World.java:955)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1490)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1342)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
> [00:27:14 ERROR]: [BKCommonLib] [BKCommonLib]   at java.base/java.lang.Thread.run(Thread.java:834)
> ```

Hey, if this is still an issue, can you open a new issue ticket? Closing this for now, since it appears to be resolved for no reason.

**Closed** 2021-08-25 08:58 UTC
Labels: A. bug (traincarts), D. cantfix
