### ISSUE TITLE
Trains not leaving timed stations when station is over 180 blocks away

### ISSUE THREAD

**Issue by goofygoff** [bergerhealer/TrainCarts#217] opened 2018-05-23 01:06 UTC
##### Spigot version:CraftBukkit 1.12.2

<hr>

#### Problem or bug:
trains do not leave stations with signs like
[train]
station
10
right
when you have timed spawners, the spawners will spawn trains and all the trains will crash into the original train after it's supposed to have left the station already.

**Comment by bbayu123** [comment] 2018-05-23 03:45
Did you power the station sign?

**Comment by goofygoff** [comment] 2018-05-24 02:09
yes

**Comment by goofygoff** [comment] 2018-05-24 02:09
or i did [!train]

**Comment by bbayu123** [comment] 2018-05-24 05:12
Did you set the config value keepChunksLoadedOnlyWhenMoving to false?

**Comment by goofygoff** [comment] 2018-05-25 00:15
whats that

**Comment by ThisTNTSquid** [comment] 2018-05-25 06:00
@goofygoff Can you tell me the delay time set on both the spawner sign and the station sign?

**Comment by ThisTNTSquid** [comment] 2018-05-25 06:14
*[for better understanding , we assumed the thing spawning at spawner is a single minecart]*

When making automated systems, the delay for spawner signs should be **longer** than the one at station as a safety buffer.


**What might happened to you:**
 If you have the same delay time on both the spawner sign and station sign, the next spawned cart will bump into the one standing on top of the station sign(which is about to depart), when the carts are at their default behavior (which is linking on collision), they will link up, forming a new train that consists of 2 minecarts. To the station sign, this is a brand new train, and would initiate stopping action once again , stopping the train with 2 minecarts with given delay (even though one cart should have been left the station already).
Even if carts do not link, the next spawned cart will still bump into the one on station, losing its velocity in front of the station (and stand right there) while the one originally standing at the station leaves. This is still breaking the automation
> The reason behind this is that station signs do not stop / start a train immediately, when a cart / train runs on top of a station sign, it will stop the train smoothly until the station sign is at the middle of the whole train. Station signs are stopping the train only when one of the member cart (mostly the first cart) touches the  rail on a station sign

**Comment by goofygoff** [comment] 2018-05-26 01:00
![2018-05-25_17 57 21](https://user-images.githubusercontent.com/39541121/40570963-70291aa8-6045-11e8-8d74-bbeb06b489c1.png)
this is the result

**Comment by goofygoff** [comment] 2018-05-26 01:01
the station sign is 5 seconds and the spawner is 45 seconds

**Comment by goofygoff** [comment] 2018-06-01 13:54
Anyone got a fix for it?

**Comment by goofygoff** [comment] 2018-06-01 13:54
Bergerhealer?

**Comment by ThisTNTSquid** [comment] 2018-06-01 13:56
Do you have a screenshot on both the spawner and the station sign?

**Comment by goofygoff** [comment] 2018-06-01 13:59
@ThisTNTSquid help meeeeeee

**Comment by ThisTNTSquid** [comment] 2018-06-01 14:05
Well.. 

> Do you have a screenshot on both the spawner and the station sign?

If you can, please also provide me with the setup details

Also double check if the trains have loadchunk property with `keepChunksLoadedOnlyWhenMoving` set to `false` in the config. In your case which trains don't depart, keepChunksLoadedOnlyWhenMoving is likely to be the cause as the trains are able to stop at station, but not departing after they stopped.

**Comment by ThisTNTSquid** [comment] 2018-06-01 14:09
Side note: If you have discord already, please consider joining/using our discord server here at https://discord.gg/P34bUPT . It should provide a much more direct and quicker support for the problem you are facing right now

**Comment by goofygoff** [comment] 2018-06-02 02:37
keepChunksLoadedOnlyWhenMoving is false

**Comment by bbayu123** [comment] 2018-06-02 02:40
We need screenshots of the signs

**Comment by goofygoff** [comment] 2018-06-04 03:05
Ok

**Comment by goofygoff** [comment] 2018-06-04 03:12
here they are
![2018-06-03_20 11 37](https://user-images.githubusercontent.com/39541121/40896539-634d1db2-676a-11e8-86ae-be8e95fc02d4.png)
![2018-06-03_20 10 38](https://user-images.githubusercontent.com/39541121/40896544-6d5ec346-676a-11e8-8c60-83f6073daba6.png)

**Comment by goofygoff** [comment] 2018-06-04 03:14
![2018-06-03_20 14 08](https://user-images.githubusercontent.com/39541121/40896603-c3105606-676a-11e8-8b36-a711533a1333.png)

**Comment by bbayu123** [comment] 2018-06-04 03:15
Aah..

**Comment by bbayu123** [comment] 2018-06-04 03:15
You see that line "Keep nearby chunks loaded: false"?
It needs to be set to true

**Comment by goofygoff** [comment] 2018-06-04 17:04
how do u change it? also, how do i set it so that it doesn't stop when a horse or mob or player hits it?

**Comment by bbayu123** [comment] 2018-06-05 02:16
you add 3 property signs after the train spawns
![image](https://user-images.githubusercontent.com/26726381/40951365-232dc8a4-68a9-11e8-8c9c-d2817fc412a4.png)
![image](https://user-images.githubusercontent.com/26726381/40951380-3ed42e4a-68a9-11e8-92ab-3fba4a051d26.png)
![image](https://user-images.githubusercontent.com/26726381/40951419-75b66f04-68a9-11e8-81c5-ff3b88e19b9c.png)

**Comment by bbayu123** [comment] 2018-06-09 10:14
Is this issue resolved yet?

**Comment by ThisTNTSquid** [comment] 2018-06-14 05:59
Is the issue resolved? If yes please close the issue

**Closed** 2018-11-12 19:29 UTC
Labels: misunderstanding of usage, resolved (requires changes by user)
