### ISSUE TITLE
Hopper Cart 

### ISSUE THREAD

**Issue by JCSweetHeart** [bergerhealer/TrainCarts#387] opened 2020-08-03 11:31 UTC
BkCommonLib version: BKCommonLib-1.16.1-v1-SNAPSHOT
TrainCarts version: TrainCarts-1.16.1-v1-SNAPSHOT
Spigot version: 1.16.1

Problem or bug:  I wil start to create a automaticly Farm for Eggs but the HopperCarts absorb into the hopper any Item and i understand why, the Hoppercart is driving but not sucking as the same when i place a Farmland over the Cart. as Example

FARMLAND (Layer 1)
HOPPERCART (Layer 2)
TRACK (Powered Rail for a lot of the Track) (Layer 3)

Expected behaviour: -----

Steps to reproduce: ----

**Comment by Andre601** [comment] 2020-08-03 12:16
Your issue doesn't make much sense...
**What exactly** is theissue?

**Comment by JCSweetHeart** [comment] 2020-08-03 12:29
As when i wil use a Hopper Cart and over the Hoppercart is Farmland, normally the Cart absorb the Item over it but momently this isn`t work :'(.

Im not sure it is a Problem of Traincart or not - exactly for that i have start this Issue

**Comment by bergerkiller** [comment] 2020-08-03 13:03
I haven't heard of this (vanilla?) feature before. You mean a farmland with a crop on it that is mature can be picked up by a hopper minecart? Or do you mean something else caused the crop to drop an item?

**Comment by Andre601** [comment] 2020-08-03 13:04
I think they mean that hopper minecarts can pick up items on farm land (which they should)

**Comment by JCSweetHeart** [comment] 2020-08-03 13:25
Exactly that i mean but isn`t work on my Server and i understand why
> 
> 
> I think they mean that hopper minecarts can pick up items on farm land (which they should)

**Comment by bbayu123** [comment] 2020-08-03 14:08
I verified with a fresh install of 1.16.1, hoppers do indeed work as intended with TrainCarts, the problems lies on your server. Are you able to tell us more information about your server, for example, plugins and specific build numbers?

**Comment by JCSweetHeart** [comment] 2020-08-03 14:46
Of Course .. here the Datas:

1) BKCommonLib-1.16.1-v1-SNAPSHOT
2) DecoHeads (Version: 1.5.0)
3) Elevators v2
4) FarmingUpgrade (Version: 1.2.2)
5) Minepacks (Version for 1.16.1 - correctly Versionnumber momently unknown)
6) SavageDeathChest (Version 1.13.3)
7) SignLink (Maybe!(!): Version 1.15.1 - havn`t found a correctly Version for 1.16.1)
8) TCCoasters-1.16.1-v1-SNAPSHOT
9) TrainCarts-1.16.1-v1-SNAPSHOT
10) TreeFeller-1.13.2
11) worldedit-bukkit-7.2.0-beta-01

Thats was - normally, when im not wrong, working all the Mods together really good .. hope anybody can me help for the Problem.

**Comment by JCSweetHeart** [comment] 2020-08-04 08:34
Hello,

as normally the Hoppercart absorb a Item above a Block but momently the HopperCarts not make this. I use all the Mods above and the currently Spigot - Version for 1.16.1. After a restart i have the same Problem. When anybody as example bbayu123 oder bergerkiller help me, i can send you Gays private the IP of my Server that we can look about this Problem.

**Comment by bbayu123** [comment] 2020-08-04 08:36
well, I'd appreciate a video first, as the language barrier has been proven to be difficult to break down in order to help you

**Comment by JCSweetHeart** [comment] 2020-08-04 08:39
How i can here send a Video or is Link to a private Youtube - Movie ok?

**Comment by bbayu123** [comment] 2020-08-04 08:41
that's good, but remember don't put it on private, put it on unlisted or else we can't see it

**Comment by JCSweetHeart** [comment] 2020-08-04 08:49
Ok, i upload it momently and edit this post when i have the link for the Video

**Comment by bbayu123** [comment] 2020-08-04 09:46
Maybe I should have asked this first, are you able to replicate this issue without any plugins installed?

**Comment by JCSweetHeart** [comment] 2020-08-04 10:01
It`s work without Mods in MC 1.16.1 in Singleplayer --> See this Video: https://youtu.be/JovH_MZKclM

> 
> 
> Maybe I should have asked this first, are you able to replicate this issue without any plugins installed?

**Comment by bbayu123** [comment] 2020-08-04 10:03
don't test in single player, test in multiplayer, the same exact server but with all mods removed

**Comment by bbayu123** [comment] 2020-08-04 10:03
the problem has something to do with your server, traincarts has nothing to do with it

**Comment by Andre601** [comment] 2020-08-04 10:04
Just to clarify: Those a plugins, not mods. It's a significant difference and calling one the other is wrong.

**Comment by JCSweetHeart** [comment] 2020-08-04 10:32
Ok i try it now but this Time without Video ^^

**Comment by JCSweetHeart** [comment] 2020-08-04 10:35
Without Mods it`s works fine as the same in Singleplayer

> Ok i try it now but this Time without Video ^^

**Comment by JCSweetHeart** [comment] 2020-08-04 10:41
Ok i have remove FarmingUpgrade (Version: 1.2.2) and WorldEdit and now it`s work but i understand why

**Comment by bbayu123** [comment] 2020-08-04 11:09
try putting worldedit back onto your server and see if it still works, if it still works then it's a problem with FarmingUpgrade

**Comment by bbayu123** [comment] 2021-05-28 07:12
Closing as this has nothing to do with TrainCarts.

**Closed by bbayu123** 2021-05-28 07:12 UTC
Labels: A. bug (other), D. cantfix
