### ISSUE TITLE
Teleporter from myworld does not seems to work.

### ISSUE THREAD

**Issue by fresser** [bergerhealer/TrainCarts#48] opened 2016-02-10 17:20 UTC
I have tried tons of different things to try make this work. But i cannot get a train to teleport, as described here.
http://minecraft.gamepedia.com/Custom_servers/Bukkit/TrainCarts/Signs/Teleporter

I have powered both signs, and they are in 2 different worlds. Is the feature deprecated?

**Comment by mg-1999** [comment] 2016-02-10 18:28
I've checked it out and is seems to be a bug. Gonna debug it in  the following days and hopefully come with a solution.

**Comment by fresser** [comment] 2016-02-10 19:34
Nice. Anyhow, i found this issue in here, that i didn't find as first. Seems like the same problem and behavior. #45

**Comment by mg-1999** [comment] 2016-02-11 00:09
That is indeed the same issue. Didn't notice it because i looked in the wrong place :P

**Comment by fresser** [comment] 2016-02-11 07:17
So, not to stress you, but is there planned a fix to this? Because if not, we will not be able to use this for our server unfortunately. :3

**Comment by FriwiDev** [comment] 2016-02-12 14:15
Duplicate of #35

**Closed** 2016-02-12 14:14 UTC
Labels: bug
