### ISSUE TITLE
Minecart bug

### ISSUE THREAD

**Issue by happylucas742003** [bergerhealer/TrainCarts#43] opened 2016-01-09 17:40 UTC
Hello i found a bug, when the minecarts are moving one of the minecarts go through the ground.

**Comment by mg-1999** [comment] 2016-01-09 19:37
Can you provide more information? Like spigot, bkcommonlib and traincarts version? Any other plugins you have installed? And maybe a screenshot or a video?

**Comment by happylucas742003** [comment] 2016-01-11 15:19
I got some screen shots 
![2016-01-11_16 18 19](https://cloud.githubusercontent.com/assets/7580384/12237442/fa1897be-b87e-11e5-973a-f7cec7596752.png)
![2016-01-11_16 18 08](https://cloud.githubusercontent.com/assets/7580384/12237446/fefb4538-b87e-11e5-93d0-ec2ebaf66227.png)

The park plugin is just a custom made with fountains

**Comment by happylucas742003** [comment] 2016-01-11 15:27
Btw im using spigot  1.8.8-R0.1

**Comment by mg-1999** [comment] 2016-01-14 16:36
Check if #20 could help you.

**Comment by gixmy** [comment] 2016-02-15 21:49
I'm having a very similar issue if not the same. A single minecart sinks into the ground at the same spot every time I run between two stations. 

Point where the minecart always sinks into the ground:
![2016-02-15_21 20 36](https://cloud.githubusercontent.com/assets/7560737/13060948/ceb5069c-d42c-11e5-98d1-b3e31d78f094.png)

Riding on a minecart that has just sunk below the rail:
![2016-02-15_21 37 35](https://cloud.githubusercontent.com/assets/7560737/13060976/010813fa-d42d-11e5-8b26-ca1b157ade93.png)

After getting out of the minecart - minecart now hidden underground:
![2016-02-15_21 37 50](https://cloud.githubusercontent.com/assets/7560737/13061002/2004113c-d42d-11e5-8ca1-2cf2fce12712.png)

Minecart revealed underneath:
![2016-02-15_21 37 56](https://cloud.githubusercontent.com/assets/7560737/13061052/5ce459e0-d42d-11e5-80ed-8432d625b246.png)

I'm running spigot 1.8.8 which I built using the BuildTools.jar, BKCommonLib v1.67-SNAPSHOT and Train_Carts v1.75-SNAPSHOT.

I've also noticed that minecarts don't always sit square on to the rail.

**Comment by woeterman94** [comment] 2016-03-11 14:18
I have the exact same problem as gixmy. 
see https://github.com/bergerhealer/TrainCarts/issues/53

**Comment by gixmy** [comment] 2016-03-13 12:16
I have now found a workaround for this issue - well my daughter did... 

If you place a powered rail that has no power before the point where the glitch normally happens, then the minecart passes without glitching. I'm guessing that passing over a powered rail with no power corrects the y position errors that are accumulating hence stopping the glitch. 

The non powered rail can be placed just before the point where the glitch happens or 100s of blocks before. That doesn't appear to make a difference. As long as the error hasn't accumulated too much it should be ok.

So far I have found 2 points where minecarts are sinking into the ground at the bottom of slopes. Both have been fixed by having my minecart go over a non powered rail before reaching the point where previously it sank into the floor.

**Comment by woeterman94** [comment] 2016-03-13 19:00
Exception 
6:59:41 PM [SEVERE] [Train_Carts] Failed to perform physics on train 'train1' at world_-703_24_1012:
6:59:41 PM [SEVERE] java.lang.NullPointerException

**Comment by woeterman94** [comment] 2016-03-13 19:06
When going in the train and doing /info

7:06:17 PM [WARNING] java.lang.NullPointerException
7:06:17 PM [WARNING] 	at com.bergerkiller.bukkit.tc.commands.TrainCommands.info(TrainCommands.java:470)
7:06:17 PM [WARNING] 	at com.bergerkiller.bukkit.tc.commands.TrainCommands.execute(TrainCommands.java:35)
7:06:17 PM [WARNING] 	at com.bergerkiller.bukkit.tc.commands.Commands.execute(Commands.java:52)
7:06:17 PM [WARNING] 	at com.bergerkiller.bukkit.tc.TrainCarts.command(TrainCarts.java:630)
7:06:17 PM [WARNING] 	at com.bergerkiller.bukkit.common.PluginBase.onCommand(PluginBase.java:837)
7:06:17 PM [WARNING] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
7:06:17 PM [WARNING] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
7:06:17 PM [WARNING] 	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
7:06:17 PM [WARNING] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
7:06:17 PM [WARNING] 	at java.util.concurrent.FutureTask.run(Unknown Source)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:714)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653)
7:06:17 PM [WARNING] 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556)
7:06:17 PM [WARNING] 	at java.lang.Thread.run(Unknown Source)

**Comment by Mr-toaster111** [comment] 2016-03-13 19:20
What versions are you using? It will not work on 1.9.

**Comment by woeterman94** [comment] 2016-03-13 20:14
I'm using 1.8

**Comment by Mr-toaster111** [comment] 2016-03-13 20:28
Do /ver BKCommonlib, /ver TrainCarts and /ver. Print the results here

**Comment by gixmy** [comment] 2016-03-14 06:41
How does the exceptions being reported by woeterman94 have anything to do with the glitches that this issue is meant to be about? Shouldn't they been documented in a new issue?

**Comment by Mr-toaster111** [comment] 2016-03-14 10:38
Yes they should

**Comment by woeterman94** [comment] 2016-03-14 12:20
@gixmy I posted my own Issue thread but it was closed and flagged as duplicate.

**Comment by gixmy** [comment] 2016-03-14 12:29
Yes because it appears to be a duplicate of this one. Each issue raised here is meant to be about one issue. You don't own an issue thread. When you see a new issue, you create a new issue report on github for it, that's assuming no one else has already created one for the issue you have seen.

**Comment by woeterman94** [comment] 2016-03-14 12:32
@gixmy Agree. So don't complain that the error message is not related to your issue. Because it is relevant to the issue I posted.

![2](https://cloud.githubusercontent.com/assets/5755057/13704449/58a07b70-e79c-11e5-93c9-4c4a16263ef7.png)

The error appears on console when a train randomly 'splits' and stops moving.
Exception 
6:59:41 PM [SEVERE] [Train_Carts] Failed to perform physics on train 'train1' at world_-703_24_1012:
6:59:41 PM [SEVERE] java.lang.NullPointerException

**Comment by gixmy** [comment] 2016-03-14 12:53
Looking at what you posted on #53, do you have two issues? 

 - minecart randomly stops
 - minecart sinks into the ground.

This issue documents the sinking into the ground - read the OP first post above. 

Personally I think the randomly stops issue should have its own thread. More information is needed for the physics null ptr exception that you reported above. When is this happening exactly? Is it when the cart sinks into the floor or stops? Why didn't you report this previously? What has changed if this has just started happening? 

Also what about reporting the outputs from /ver BKCommonlib, /ver Train_Carts and /ver as requested above.

**Comment by Mr-toaster111** [comment] 2016-03-14 13:12
Yes please understand that traincarts will NOT function on the spigot 1.9 build. A lot of people are getting confused by this.

**Comment by woeterman94** [comment] 2016-03-14 13:16
It is not 1.9 how often will I need to confirm that :/  I'm using 1.8.9. 

I will post a full server log,/ver BKCommonlib, /ver Train_Carts and /ver as requested when I'm home.

**Comment by woeterman94** [comment] 2016-03-14 13:21
Issue seems to mostly when a train moves from a angled rail to a flat rail.

**Comment by gixmy** [comment] 2016-03-14 13:24
> Issue seems to mostly when a train moves from a angled rail to a flat rail. 

Sorry but which issue are you talking about now?

**Comment by woeterman94** [comment] 2016-03-30 07:47
What more info do you need?

**Comment by Kadaverschreck** [comment] 2016-04-27 16:17
I got the same problem yesterday. After trying the non-powered-rail, as gixmy said, the problem was still there. For me it helped to put a stone_pressure_plate on the ground where the cart sunks down. For secure driving i put a second plate after the first. Maybe the Information helps mg and others with same problem.

**Comment by 72juju** [comment] 2016-07-22 12:27
;(

**Comment by woeterman94** [comment] 2016-10-12 14:03
bug opened on 9 jan. Nine months later... Still not fixed.

**Comment by bergerkiller** [comment] 2017-04-19 08:11
Didn't realize this bug was so old! Anyway, this was a 'slope bug' where going downslope caused the minecart block position to fall down below y=0, causing it to be inside the block down the slope. Because minecart block collision is so wonky the minecart went through the block. This is now fixed after a slight rewrite of the sloped rail logic and adding a dy >= 0.063 limit in the physics.

**Closed by bergerkiller** 2017-04-19 08:11 UTC
Labels: needs more info

**Comment by Totti1992DE** [comment] 2017-05-24 21:59
Same problem like gixmy. Powered rails or pressure plates didn't helped.
Using Spigot 1.8.8 and the newest (?) TrainCarts-version (1.8downloadfix) from Spigot.
Is there a fix for this bug? Thanks!
